config/routes.rb
# == Route Map
#
#                    Prefix Verb   URI Pattern                                                                              Controller#Action
#                  projects GET    /projects(.:format)                                                                      projects#index
#                           POST   /projects(.:format)                                                                      projects#create
#               new_project GET    /projects/new(.:format)                                                                  projects#new
#              edit_project GET    /projects/:id/edit(.:format)                                                             projects#edit
#                   project GET    /projects/:id(.:format)                                                                  projects#show
#                           PATCH  /projects/:id(.:format)                                                                  projects#update
#                           PUT    /projects/:id(.:format)                                                                  projects#update
#                           DELETE /projects/:id(.:format)                                                                  projects#destroy
#          new_user_session GET    /users/sign_in(.:format)                                                                 devise/sessions#new
#              user_session POST   /users/sign_in(.:format)                                                                 devise/sessions#create
#      destroy_user_session DELETE /users/sign_out(.:format)                                                                devise/sessions#destroy
#         new_user_password GET    /users/password/new(.:format)                                                            devise/passwords#new
#        edit_user_password GET    /users/password/edit(.:format)                                                           devise/passwords#edit
#             user_password PATCH  /users/password(.:format)                                                                devise/passwords#update
#                           PUT    /users/password(.:format)                                                                devise/passwords#update
#                           POST   /users/password(.:format)                                                                devise/passwords#create
#  cancel_user_registration GET    /users/cancel(.:format)                                                                  devise/registrations#cancel
#     new_user_registration GET    /users/sign_up(.:format)                                                                 devise/registrations#new
#    edit_user_registration GET    /users/edit(.:format)                                                                    devise/registrations#edit
#         user_registration PATCH  /users(.:format)                                                                         devise/registrations#update
#                           PUT    /users(.:format)                                                                         devise/registrations#update
#                           DELETE /users(.:format)                                                                         devise/registrations#destroy
#                           POST   /users(.:format)                                                                         devise/registrations#create
#                      root GET    /                                                                                        devise/sessions#new
#                    models GET    /models(.:format)                                                                        models#index
#                           POST   /models(.:format)                                                                        models#create
#                 new_model GET    /models/new(.:format)                                                                    models#new
#                edit_model GET    /models/:id/edit(.:format)                                                               models#edit
#                     model GET    /models/:id(.:format)                                                                    models#show
#                           PATCH  /models/:id(.:format)                                                                    models#update
#                           PUT    /models/:id(.:format)                                                                    models#update
#                           DELETE /models/:id(.:format)                                                                    models#destroy
#                   repairs GET    /repairs(.:format)                                                                       repairs#index
#                           POST   /repairs(.:format)                                                                       repairs#create
#                new_repair GET    /repairs/new(.:format)                                                                   repairs#new
#               edit_repair GET    /repairs/:id/edit(.:format)                                                              repairs#edit
#                    repair GET    /repairs/:id(.:format)                                                                   repairs#show
#                           PATCH  /repairs/:id(.:format)                                                                   repairs#update
#                           PUT    /repairs/:id(.:format)                                                                   repairs#update
#                           DELETE /repairs/:id(.:format)                                                                   repairs#destroy
#                  comments GET    /comments(.:format)                                                                      comments#index
#                           POST   /comments(.:format)                                                                      comments#create
#               new_comment GET    /comments/new(.:format)                                                                  comments#new
#              edit_comment GET    /comments/:id/edit(.:format)                                                             comments#edit
#                   comment GET    /comments/:id(.:format)                                                                  comments#show
#                           PATCH  /comments/:id(.:format)                                                                  comments#update
#                           PUT    /comments/:id(.:format)                                                                  comments#update
#                           DELETE /comments/:id(.:format)                                                                  comments#destroy
#                 computers GET    /computers(.:format)                                                                     computers#index
#                           POST   /computers(.:format)                                                                     computers#create
#              new_computer GET    /computers/new(.:format)                                                                 computers#new
#             edit_computer GET    /computers/:id/edit(.:format)                                                            computers#edit
#                  computer GET    /computers/:id(.:format)                                                                 computers#show
#                           PATCH  /computers/:id(.:format)                                                                 computers#update
#                           PUT    /computers/:id(.:format)                                                                 computers#update
#                           DELETE /computers/:id(.:format)                                                                 computers#destroy
#        rails_service_blob GET    /rails/active_storage/blobs/:signed_id/*filename(.:format)                               active_storage/blobs#show
# rails_blob_representation GET    /rails/active_storage/representations/:signed_blob_id/:variation_key/*filename(.:format) active_storage/representations#show
#        rails_disk_service GET    /rails/active_storage/disk/:encoded_key/*filename(.:format)                              active_storage/disk#show
# update_rails_disk_service PUT    /rails/active_storage/disk/:encoded_token(.:format)                                      active_storage/disk#update
#      rails_direct_uploads POST   /rails/active_storage/direct_uploads(.:format)                                           active_storage/direct_uploads#create

Rails.application.routes.draw do
  resources :equipment
  resources :projects
  devise_for :users
   
devise_scope :user do
 root :to => 'devise/sessions#new'
end


  resources :models
  resources :repairs
  resources :comments

 


   #root to: "/user/sign_in"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

 #config.assets.prefix = '/assetz'

end

app/models/equipment.rb
# == Schema Information
#
# Table name: equipment
#
#  id         :bigint(8)        not null, primary key
#  name       :string(255)
#  tag        :string(255)
#  serial     :string(255)
#  type       :string(255)
#  model      :string(255)
#  maker      :string(255)
#  details    :text(65535)
#  project_id :integer
#  ticket_id  :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Equipment < ApplicationRecord
end

app/controllers/equipment_controller.rb
class EquipmentController < ApplicationController
  before_action :set_equipment, only: [:show, :edit, :update, :destroy]

  # GET /equipment
  # GET /equipment.json
  def index
    @equipment = Equipment.all
  end

  # GET /equipment/1
  # GET /equipment/1.json
  def show
  end

  # GET /equipment/new
  def new
    @equipment = Equipment.new
  end

  # GET /equipment/1/edit
  def edit
  end

  # POST /equipment
  # POST /equipment.json
  def create
    @equipment = Equipment.new(equipment_params)

    respond_to do |format|
      if @equipment.save
        format.html { redirect_to @equipment, notice: 'Equipment was successfully created.' }
        format.json { render :show, status: :created, location: @equipment }
      else
        format.html { render :new }
        format.json { render json: @equipment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /equipment/1
  # PATCH/PUT /equipment/1.json
  def update
    respond_to do |format|
      if @equipment.update(equipment_params)
        format.html { redirect_to @equipment, notice: 'Equipment was successfully updated.' }
        format.json { render :show, status: :ok, location: @equipment }
      else
        format.html { render :edit }
        format.json { render json: @equipment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /equipment/1
  # DELETE /equipment/1.json
  def destroy
    @equipment.destroy
    respond_to do |format|
      format.html { redirect_to equipment_index_url, notice: 'Equipment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_equipment
      @equipment = Equipment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def equipment_params
      params.require(:equipment).permit(:name, :tag, :serial, :type, :model, :maker, :details, :project_id, :ticket_id)
    end
end

app/helpers/equipment_helper.rb
module EquipmentHelper
end

app/views/equipment/_form.html.erb
<%= bootstrap_form_for(@equipment) do |form| %>
  <% if equipment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(equipment.errors.count, "error") %> prohibited this asset from being saved:</h2>

      <ul>
      <% equipment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="container-fluid">
	<div class="row">
		<div class="col-md-12">
			<div class="row">
				<div class="col-md-2">
				</div>
				<div class="col-md-8">
        <div class="field">

    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.text_field :tag %>
  </div>

  <div class="field">
  
    <%= form.text_field :serial %>
  </div>

  <div class="field">

      <%= form.select :type, options_for_select([["Computer"], ["Screen"],["Mouse"],  ["Keyboard"] , ["SSD"], ["HDD"],["HDMI Adapter"],["GPU"]], :selected => @equipment.type), {}  %>
 
  
  </div>

  <div class="field">
 
    <%= form.text_field :model %>
  </div>

  <div class="field">
 
    <%= form.text_field :maker %>
  </div>

  <div class="field">
   
    <%= form.text_area :details %>
  </div>

  <div class="field">
    
    <%= form.text_field :project_id %>
  </div>

  <div class="field">
    
    <%= form.text_field :ticket_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
				</div>
				<div class="col-md-2">
				</div>
			</div>
		</div>
	</div>
</div>

  
<% end %>

app/views/equipment/edit.html.erb
<h1>Editing Equipment</h1>

<%= render 'form', equipment: @equipment %>

<%= link_to 'Show', @equipment %> |
<%= link_to 'Back', equipment_index_path %>

app/views/equipment/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Equipment</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Tag</th>
      <th>Serial</th>
      <th>Type</th>
      <th>Model</th>
      <th>Maker</th>
      <th>Details</th>
      <th>Project</th>
      <th>Ticket</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @equipment.each do |equipment| %>
      <tr>
        <td><%= equipment.name %></td>
        <td><%= equipment.tag %></td>
        <td><%= equipment.serial %></td>
        <td><%= equipment.type %></td>
        <td><%= equipment.model %></td>
        <td><%= equipment.maker %></td>
        <td><%= equipment.details %></td>
        <td><%= equipment.project_id %></td>
        <td><%= equipment.ticket_id %></td>
        <td><%= link_to 'Show', equipment %></td>
        <td><%= link_to 'Edit', edit_equipment_path(equipment) %></td>
        <td><%= link_to 'Destroy', equipment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Equipment', new_equipment_path %>

app/views/equipment/new.html.erb
<h1>New Equipment</h1>

<%= render 'form', equipment: @equipment %>

<%= link_to 'Back', equipment_index_path %>

app/views/equipment/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @equipment.name %>
</p>

<p>
  <strong>Tag:</strong>
  <%= @equipment.tag %>
</p>

<p>
  <strong>Serial:</strong>
  <%= @equipment.serial %>
</p>

<p>
  <strong>Type:</strong>
  <%= @equipment.type %>
</p>

<p>
  <strong>Model:</strong>
  <%= @equipment.model %>
</p>

<p>
  <strong>Maker:</strong>
  <%= @equipment.maker %>
</p>

<p>
  <strong>Details:</strong>
  <%= @equipment.details %>
</p>

<p>
  <strong>Project:</strong>
  <%= @equipment.project_id %>
</p>

<p>
  <strong>Ticket:</strong>
  <%= @equipment.ticket_id %>
</p>

<%= link_to 'Edit', edit_equipment_path(@equipment) %> |
<%= link_to 'Back', equipment_index_path %>